exports.category = [
    { name: "Shoes" },
    { name: "Clothing" },
    { name: "Electronics" },
    { name: "Home & Kitchen" },
    { name: "Beauty & Personal Care" },
    { name: "Sports & Outdoors" },
    { name: "Toys & Games" },
    { name: "Furniture" },
    { name: "Jewelry" },
    { name: "Watches" },
    { name: "Luggage & Travel" },
    { name: "Automotive" },
    { name: "Office Supplies" },
    { name: "Pet Supplies" },
    { name: "Health & Household" },
    { name: "Baby" },
    { name: "Books" },
    { name: "Movies & TV" },
    { name: "Music" },
    { name: "Video Games" },
    { name: "Computers & Accessories" },
    { name: "Cameras & Photo" },
    { name: "Smartphones & Accessories" },
    { name: "Appliances" },
    { name: "Tools & Home Improvement" },
    { name: "Outdoors & Gardening" },
    { name: "Sporting Goods" },
    { name: "Exercise & Fitness" },
    { name: "Arts, Crafts & Sewing" },
    { name: "Grocery & Gourmet Food" },
    { name: "Wine, Beer & Spirits" },
    { name: "Industrial & Scientific" },
    { name: "Handmade" },
    { name: "Collectibles & Fine Art" },
    { name: "Musical Instruments" },
    { name: "Kindle Store" },
    { name: "Clothing Accessories" },
    { name: "Jewelry & Watches" },
    { name: "Shoes, Handbags & Sunglasses" },
    { name: "Men's Fashion" },
    { name: "Women's Fashion" },
    { name: "Girls' Fashion" },
    { name: "Boys' Fashion" },
    { name: "Deals" },
    { name: "Luxury Stores" },
    { name: "Luxury Beauty" },
    { name: "Prime Pantry" },
    { name: "Amazon Warehouse" },
    { name: "Amazon Renewed" },
    { name: "Amazon Outlet" },
    { name: "Gifts & Registry" },
    { name: "Pharmacy" },
    { name: "Home Services" },
    { name: "Handmade Gifts" },
    { name: "Subscription Boxes" },
    { name: "Furniture & Decor" },
    { name: "Kitchen & Dining" },
    { name: "Bed & Bath" },
    { name: "Lighting & Lamps" },
    { name: "Patio, Lawn & Garden" },
    { name: "Storage & Organization" },
    { name: "Home Improvement" },
    { name: "Smart Home" },
    { name: "Mattresses" },
    { name: "Housekeeping & Laundry" },
    { name: "Pet Supplies" },
    { name: "Clothing, Shoes & Jewelry" },
    { name: "Grocery" },
    { name: "Health, Household & Baby Care" },
    { name: "Sports & Outdoors" },
    { name: "Toys & Games" },
    { name: "Tools & Home Improvement" },
    { name: "Beauty & Personal Care" },
    { name: "Automotive" },
    { name: "Industrial & Scientific" },
    { name: "Pet Supplies" }
  ]